### ISSUE TITLE
Why no dump for engine2.dll?

### ISSUE THREAD

**Issue by aeo24** [praydog/Source2Gen#1]

**Comment by praydog** [comment]
There are Schema definitions in engine2.dll, but they are assigned to the !GlobalTypes type scope I believe. engine2.dll doesn't have its own CSchemaSystemTypeScope assigned to it. 

Any Schema definitions you find in there are actually dumped into !GlobalTypes_classes.hpp, among with many other DLLs. Just ctrl+f engine2 in that file and find out.
