### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by RadicalRedemption** [praydog/Source2Gen#9]
All generated files have around 4/5 lines of code and thats all.

**Comment by Jerffelly** [comment]
Because it's outdated.

**Comment by RadicalRedemption** [comment]
Can i have an email/skype/discord or something else to contact with you? I really need to ask a few questions.

**Comment by lynch-a** [comment]
how about you just post your questions in the open

**Comment by RadicalRedemption** [comment]
Well, i need some help with making the SDK to work..
